---
# === SOC TOOLS ROLE (TheHive Standalone Install) ===

# Step 1: Dependencies
- name: Install base dependencies
  apt:
    name:
      - wget
      - curl
      - gnupg
      - coreutils
      - apt-transport-https
      - git
      - ca-certificates
      - ca-certificates-java
      - software-properties-common
      - python3-pip
      - lsb-release
      - unzip
    update_cache: yes
    state: present

# Step 2: Amazon Corretto Java 11
- name: Add Amazon Corretto GPG key
  shell: |
    wget -qO- https://apt.corretto.aws/corretto.key | gpg --dearmor -o /usr/share/keyrings/corretto.gpg
  args:
    creates: /usr/share/keyrings/corretto.gpg

- name: Add Corretto repository
  copy:
    dest: /etc/apt/sources.list.d/corretto.sources.list
    content: |
      deb [signed-by=/usr/share/keyrings/corretto.gpg] https://apt.corretto.aws stable main

- name: Install Java 11 (Amazon Corretto)
  apt:
    name:
      - java-common
      - java-11-amazon-corretto-jdk
    update_cache: yes
    state: present

- name: Set JAVA_HOME
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME="/usr/lib/jvm/java-11-amazon-corretto"'
    create: yes

# Step 3: Cassandra installation
- name: Add Cassandra GPG key
  shell: |
    wget -qO - https://downloads.apache.org/cassandra/KEYS | gpg --dearmor -o /usr/share/keyrings/cassandra-archive.gpg
  args:
    creates: /usr/share/keyrings/cassandra-archive.gpg

- name: Add Cassandra repo
  copy:
    dest: /etc/apt/sources.list.d/cassandra.sources.list
    content: |
      deb [signed-by=/usr/share/keyrings/cassandra-archive.gpg] https://debian.cassandra.apache.org 41x main

- name: Install Cassandra
  apt:
    name: cassandra
    update_cache: yes
    state: present
- name: Ensure Cassandra data directory has correct permissions
  ansible.builtin.file:
    path: "/var/lib/cassandra"
    owner: cassandra
    group: cassandra
    state: directory
    mode: "0755"
    recurse: yes

- name: Configure cassandra.yaml
  lineinfile:
    path: /etc/cassandra/cassandra.yaml
    regexp: '^cluster_name:'
    line: "cluster_name: 'thp'"
    backrefs: yes

- name: Enable Cassandra authentication
  blockinfile:
    path: /etc/cassandra/cassandra.yaml
    block: |
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer

- name: Restart and enable Cassandra
  systemd:
    name: cassandra
    enabled: yes
    state: restarted

# Step 3.4–3.6 (Cassandra user/keyspace creation)
- name: Wait for Cassandra port
  wait_for:
    port: 9042
    delay: 15
    timeout: 60

- name: Set Cassandra admin password
  shell: |
    cqlsh -u cassandra -p cassandra -e "ALTER USER cassandra WITH PASSWORD 'AdminCassandra123';"
  ignore_errors: true

- name: Create keyspace and role for TheHive
  shell: |
    cqlsh -u cassandra -p AdminCassandra123 -e "
    CREATE KEYSPACE IF NOT EXISTS thehive WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
    CREATE ROLE IF NOT EXISTS thehive WITH LOGIN = true AND PASSWORD = '{{ thehive_role_password }}';
    GRANT ALL PERMISSIONS ON KEYSPACE thehive TO thehive;"
  args:
    executable: /bin/bash

# Step 5.1: Install TheHive
- name: Download TheHive DEB package
  get_url:
    url: "https://thehive.download.strangebee.com/5.5/deb/thehive_{{ thehive_version }}_all.deb"
    dest: "/tmp/thehive_{{ thehive_version }}_all.deb"

- name: Install TheHive
  apt:
    deb: "/tmp/thehive_{{ thehive_version }}_all.deb"
    state: present

# Step 5.4: Create file storage
- name: Create TheHive file storage directory
  file:
    path: /opt/thp/thehive/files
    state: directory
    owner: thehive
    group: thehive
    mode: "0700"
    recurse: yes

# Step 5.2: Configure TheHive
- name: Deploy application.conf
  template:
    src: application.conf.j2
    dest: /etc/thehive/application.conf
    owner: root
    group: root
    mode: "0644"

# Step 5.6: Enable and start TheHive
- name: Enable and start TheHive service
  systemd:
    name: thehive
    enabled: yes
    state: started
