---
- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Add Elastic GPG key
  ansible.builtin.shell: |
    curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor | sudo tee /usr/share/keyrings/elastic-keyring.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/elastic-keyring.gpg

- name: Add Elastic APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    filename: "elastic-8.x"
    state: present

- name: Install Filebeat
  ansible.builtin.apt:
    name: filebeat
    state: present
    update_cache: yes

- name: Deploy Filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: "0644"
  notify: restart filebeat

- name: Enable and start Filebeat service
  ansible.builtin.systemd:
    name: filebeat
    enabled: yes
    state: started
