---
# ============================================================
# SNORT 3 INSTALLATION + CONFIGURATION (Official + Uni Guide)
# ============================================================

- name: Install all required dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - g++
      - make
      - libdumbnet-dev
      - flex
      - bison
      - libpcap-dev
      - libpcre2-dev
      - libluajit-5.1-dev
      - libssl-dev
      - zlib1g-dev
      - libhwloc-dev
      - pkg-config
      - git
      - autoconf
      - libtool
      # Optional but recommended
      - liblzma-dev
      - uuid-dev
      - libunwind-dev
      - libhyperscan-dev
      - libflatbuffers-dev
      # Optional for documentation / testing
      - asciidoc
      - dblatex
      - source-highlight
      - w3m
    state: present
    update_cache: yes


# ------------------------------------------------------------
# BUILD AND INSTALL LIBDAQ
# ------------------------------------------------------------
- name: Create build directory
  ansible.builtin.file:
    path: "{{ build_dir }}"
    state: directory
    mode: "0755"

- name: Clone LibDAQ repository
  ansible.builtin.git:
    repo: "https://github.com/snort3/libdaq.git"
    dest: "{{ build_dir }}/libdaq"
    version: master

- name: Bootstrap LibDAQ
  ansible.builtin.command: ./bootstrap
  args:
    chdir: "{{ build_dir }}/libdaq"

- name: Configure LibDAQ
  ansible.builtin.command: ./configure --prefix={{ daq_install_dir }}
  args:
    chdir: "{{ build_dir }}/libdaq"

- name: Build and install LibDAQ
  ansible.builtin.command: make install
  args:
    chdir: "{{ build_dir }}/libdaq"

- name: Add DAQ library path to ld.so.conf.d
  ansible.builtin.copy:
    dest: /etc/ld.so.conf.d/libdaq3.conf
    content: "{{ daq_install_dir }}/lib/\n"
    mode: "0644"

- name: Refresh dynamic linker bindings
  ansible.builtin.command: /sbin/ldconfig
  changed_when: false

# ------------------------------------------------------------
# BUILD AND INSTALL SNORT 3
# ------------------------------------------------------------
- name: Clone Snort 3 repository
  ansible.builtin.git:
    repo: "https://github.com/snort3/snort3.git"
    dest: "{{ build_dir }}/snort3"
    version: master

- name: Configure Snort 3 with DAQ paths
  ansible.builtin.command: >
    ./configure_cmake.sh
    --prefix={{ snort_install_dir }}
    --with-daq-includes={{ daq_install_dir }}/include/
    --with-daq-libraries={{ daq_install_dir }}/lib/
  args:
    chdir: "{{ build_dir }}/snort3"

- name: Compile Snort 3
  ansible.builtin.shell: make -j $(nproc)
  args:
    chdir: "{{ build_dir }}/snort3/build"

- name: Install Snort 3
  ansible.builtin.command: make install
  args:
    chdir: "{{ build_dir }}/snort3/build"

# ------------------------------------------------------------
# POST-INSTALL CONFIGURATION
# ------------------------------------------------------------
- name: Create snort group and user
  ansible.builtin.user:
    name: snort
    shell: /sbin/nologin
    comment: "Snort IDS service account"
    system: yes

- name: Create configuration and log directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: snort
    group: snort
    mode: "0755"
  loop:
    - "{{ snort_install_dir }}/etc"
    - "{{ snort_install_dir }}/rules"
    - "{{ snort_install_dir }}/logs"
    - "{{ snort_install_dir }}/lib/snort_dynamicrules"

- name: Copy default configuration
  ansible.builtin.copy:
    src: "{{ snort_install_dir }}/etc/snort_defaults.lua"
    dest: "{{ snort_install_dir }}/etc/snort.lua"
    remote_src: yes
    owner: snort
    group: snort
    mode: "0644"

# ------------------------------------------------------------
# DOWNLOAD RULES
# ------------------------------------------------------------
- name: Download community rules
  ansible.builtin.get_url:
    url: https://www.snort.org/downloads/community/snort3-community-rules.tar.gz
    dest: /tmp/snort3-community-rules.tar.gz

- name: Extract community rules
  ansible.builtin.unarchive:
    src: /tmp/snort3-community-rules.tar.gz
    dest: "{{ snort_install_dir }}/rules"
    remote_src: yes
    extra_opts: ["--strip-components=1"]
    owner: snort
    group: snort

# ------------------------------------------------------------
# SYSTEMD SERVICE
# ------------------------------------------------------------
- name: Deploy Snort 3 systemd service
  ansible.builtin.template:
    src: snort3.service.j2
    dest: /etc/systemd/system/snort3.service
    mode: "0644"

- name: Enable and start snort3 service
  ansible.builtin.systemd:
    name: snort3
    enabled: yes
    state: started

# ------------------------------------------------------------
# VERIFICATION
# ------------------------------------------------------------
- name: Check Snort version
  ansible.builtin.command: "{{ snort_install_dir }}/bin/snort -V"
  register: snort_version_output
  ignore_errors: yes

- name: Display Snort version info
  ansible.builtin.debug:
    var: snort_version_output.stdout

- name: Verify DAQ modules
  ansible.builtin.command: >
    {{ snort_install_dir }}/bin/snort
    --daq-dir {{ daq_install_dir }}/lib/daq
    --daq-list
  register: daq_modules_output
  ignore_errors: yes

- name: Display DAQ modules
  ansible.builtin.debug:
    var: daq_modules_output.stdout
