---
- name: restart gvmd
  ansible.builtin.service:
    name: gvmd
    state: restarted

- name: restart gsad
  ansible.builtin.service:
    name: gsad
    state: restarted

- name: restart ospd-openvas
  ansible.builtin.service:
    name: ospd-openvas
    state: restarted

- name: restart notus-scanner
  ansible.builtin.service:
    name: notus-scanner
    state: restarted

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
