---
# ===== ELASTICSEARCH =====
- name: Ensure Elasticsearch systemd service is reloaded and enabled
  listen: restart elasticsearch
  become: yes
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    state: stopped          # Stop during image build
    daemon_reload: yes


# ===== KIBANA =====
- name: Ensure Kibana systemd service is reloaded and enabled
  listen: restart kibana
  ansible.builtin.systemd:
    name: kibana
    enabled: true
    state: stopped
    daemon_reload: yes

# ===== LOGSTASH =====
- name: Ensure Logstash systemd service is reloaded and enabled
  listen: restart logstash
  ansible.builtin.systemd:
    name: logstash
    enabled: true
    state: stopped
    daemon_reload: yes

# ===== FILEBEAT =====
- name: Ensure Filebeat systemd service is reloaded and enabled
  listen: restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    enabled: true
    state: stopped
    daemon_reload: yes

# ===== WAZUH MANAGER =====
- name: Ensure Wazuh Manager systemd service is reloaded and enabled
  listen: restart wazuh manager
  ansible.builtin.systemd:
    name: wazuh-manager
    enabled: true
    state: stopped
    daemon_reload: yes
