---
- name: Restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted

- name: Restart Kibana
  service:
    name: kibana
    state: restarted

- name: Restart Wazuh Manager
  service:
    name: wazuh-manager
    state: restarted
