name: Build Security-Tools AMI
on:
  push:
    paths:
      - "ansible/roles/security-tools/**"
      - "packer/security-tools.pkr.hcl"
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  AWS_ROLE_SESSION_NAME: packer
  AWS_ROLE_DURATION_SECONDS: 7200
jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-packer@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::057827529833:role/GitHubActionsPipeline
          aws-region: eu-central-1
          role-duration-seconds: 7200

      - name: Build Security-Tools AMI
        run: |
          cd packer
          packer init security-tools.pkr.hcl
          packer build -debug -on-error=ask security-tools.pkr.hcl

      - name: Extract AMI ID
        id: ami
        run: |
          AMI_ID=$(jq -r '.builds[-1].artifact_id' ./packer/manifest.json | cut -d':' -f2)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
          echo "Built AMI: $AMI_ID"

      - name: Store AMI ID in SSM
        run: |
          aws ssm put-parameter \
            --name "/soar/ami/security-tools" \
            --value "$AMI_ID" \
            --type String \
            --overwrite
