name: Build Security-Tools AMI
on:
  push:
    paths:
      - 'ansible/roles/security-tools/**'
      - 'packer/security-tools.pkr.hcl'
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-packer@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::057827529833:role/GitHubActionsPipeline
          aws-region: eu-central-1
          
      - name: Build Security-Tools AMI
        run: |
          cd packer
          packer init security-tools.pkr.hcl
          packer build security-tools.pkr.hcl